server:
  port:8080

spring:
  datasource:
    username: postgres
    password: 471979
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pets
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/change-log/db.change-log.sql
