name: Java CI for Multiple Projects

on: [push, pull_request]

jobs:
  test-TypeFilter:
    name: Test TypeFilter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Install Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run tests for TypeFilter
        run: gradle test
        working-directory: TypeFilter
