name: Java CI for Multiple Projects

on: [push, pull_request]

jobs:
  test-TypeFilter:
    name: Test TypeFilter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Make gradlew usage
        run: chmod +x gradlew
        working-directory: TypeFilter

      - name: Запуск тестов для TypeFilter
        run: ./gradlew test
        working-directory: TypeFilter